### ISSUE TITLE
result is worse than regular whisper-large-v3. did I do anything wrong?

### ISSUE THREAD

**Issue by EtayZaslavsky** [ivrit-ai/ivrit.ai#54]
Used your code from hugging face, with mp3. It gave me a result that is worse than regular whisper large v3.
Did I do anything wrong?

Whisper:
אסור לך לחשוב כשאת כל כך עייפה
צילי טיול לעוזריך רחוקה מהבית
Your model:
עשו לך לחשוב כשאת כל כך חיפה צי לטיול לעוזריך רחוקה מהבית

```
import torch
import librosa
from transformers import WhisperProcessor, WhisperForConditionalGeneration

SAMPLING_RATE = 16000

# Check for CUDA availability
has_cuda = torch.cuda.is_available()

# Path to the pre-trained model
model_path = "ivrit-ai/whisper-v2-d3-e3"

# Load the model and move it to GPU if available
model = WhisperForConditionalGeneration.from_pretrained(model_path)
if has_cuda:
    model.to("cuda:0")

# Load the processor
processor = WhisperProcessor.from_pretrained(model_path)

# Load and process the MP3 file
audio_path = "ad mahar.mp3"
audio, sr = librosa.load(audio_path, sr=SAMPLING_RATE)

# Prepare the input features
input_features = processor(
    audio, sampling_rate=SAMPLING_RATE, return_tensors="pt"
).input_features
if has_cuda:
    input_features = input_features.to("cuda:0")

# Generate the transcription
predicted_ids = model.generate(input_features, language="he", num_beams=5)
transcript = processor.batch_decode(predicted_ids, skip_special_tokens=True)

# Output the transcript
with open("transcript.txt", "w") as f:
    for text in transcript:
        f.write(text + "\n")

```

**Comment by yairl** [comment]
The code provided does not generate good results, and is unfortunately not up to date.
You should use faster_whisper, as such:

```
import faster_whisper
model = faster_whisper.WhisperModel('ivrit-ai/faster-whisper-v2-d3-e3')

segs, _ = model.transcribe(file, language='he')
for s in segs:
    print(s.text)
```

**Comment by mtnsh** [comment]
> The code provided does not generate good results, and is unfortunately not up to date. You should use faster_whisper, as such:
> 
> ```
> import faster_whisper
> model = faster_whisper.WhisperModel('ivrit-ai/faster-whisper-v2-d3-e3')
> 
> segs, _ = model.transcribe(file, language='he')
> for s in segs:
>     print(s.text)
> ```

is there any limitation on file size? (e.g. couple of hours)
the basic usage from hugging face results in a poor translation with many repetitions and overall sub-par results to whisper and similar services.

I would like to ask, please provide a more thorough instructions on how to use this model.
Using it as is like hugging-face is the BKM? this is what one should expect to get as the best results from the model in it's current state?

i read the faster-whisper repo for some tweaks, but the quality of the transcription didnt change.
the audio has good quality, not studio grade.


i am using the following code from hugging face:
```
import faster_whisper
model = faster_whisper.WhisperModel('ivrit-ai/faster-whisper-v2-d4')

segs, _ = model.transcribe('media-file', language='he')

texts = [s.text for s in segs]

transcribed_text = ' '.join(texts)
print(f'Transcribed text: {transcribed_text}')
```
